name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "feature:"
        minor_pattern: "bugfix:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "iniciando"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "final"

    - name: Build Docker Image
      env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t carlosvilca/docker:lastest .
        docker build -t carlosvilca/docker:$NEW_VERSION .
        
    - name: Push Docker Image
      run: |
        docker push carlosvilca/docker:lastest
        docker push carlosvilca/docker:$NEW_VERSION

        
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
